### ISSUE TITLE
About Tab Image

### ISSUE THREAD

**Issue by todd-lm** [c22coders/sample-profile-page#6]
The About tab is working but, the image and the git link in the upper right isn't. Could be the frame, IDK

**Comment by amazansky** [comment]
Seems to be working for me...
![screen shot 2016-06-07 at 4 20 50 pm](https://cloud.githubusercontent.com/assets/11902347/15873263/d652fba0-2ccb-11e6-891e-d8d3d4d3c7d5.png)

**Comment by Tpixelminer** [comment]
❓:O

**Comment by todd-lm** [comment]
Yes, the image is working fine, the link in the upper right hand corner is not @RobotXLabs

**Comment by amazansky** [comment]
Oops... It's the frame. GH has the frame options set to no, will try to figure out a way to fix it.

**Comment by todd-lm** [comment]
Ok, great!
